name             'user'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures user'
long_description 'Installs/Configures user'
version          '0.1.0'
